package it.polimi.ingsw.cg_38.controller.event;

/** enumerazione dei tipi di evento di notifica */
public enum NotifyEventType {
	ATTACKED, 
	MOVED, 
	CARDUSED, 
	DROWN, 
	DECLAREPOSITION, 
	ADDED, 
	START, 
	ERROR, 
	NOTIFYTURN, 
	ENVIRONMENT, 
	NOISE, 
	NOTWIN, 
	NOTLOOSE, 
	ALIENSWIN,
	SUFFERATTACK, 
	USEDEFENSECARD, 
	NOTTELEPORT, 
	HUMANWIN, 
	HATCHBLOCKED, 
	CLOSINGTOPIC, 
	REJECTCARD, 
	CARDPERFORMED, 
	REJECTCARDHUMAN, 
	CLOSINGGAME, 
	CHAT, 
	RETIRED
}
